Airbnb/GreekTravel/src/java/model/BookingModel.java
package model;

//import static entities.User_.nickname;
import java.util.Date;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

public class BookingModel {

    private Integer id;
    private Date date_from;
    private Date date_to;
    private Integer owner_rating;
    private Integer room_rating;
    private UserModel visitor;

    public UserModel getVisitor() {
        return visitor;
    }

    public void setVisitor(UserModel visitor) {
        this.visitor = visitor;
    }

    public Integer getId() {
        return id;
    }

    @XmlAttribute
    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDateFrom() {
        return date_from;
    }

    @XmlElement
    public void setDateFrom(Date date_from) {
        this.date_from = date_from;
    }

    public Date getDateTo() {
        return date_to;
    }

    @XmlElement
    public void setDateTo(Date date_to) {
        this.date_to = date_to;
    }

    public Integer getOwnerRating() {
        return owner_rating;
    }

    @XmlElement
    public void setOwnerRating(Integer owner_rating) {
        this.owner_rating = owner_rating;
    }

    public Integer getRoomRating() {
        return room_rating;
    }

    @XmlElement
    public void setRoomRating(Integer room_rating) {
        this.room_rating = room_rating;
    }
}

Airbnb/GreekTravel/src/java/controllers/account/LoginController.java
package controllers.account;

import dao.UserDAOImpl;
import entities.Role;
import entities.User;
import java.util.List;
import java.util.Map;
import javax.servlet.http.HttpSession;
import validation.SkipValidator;
import validation.UserNameValidator;

public class LoginController extends controllers.Controller {

    private UserDAOImpl dao = new UserDAOImpl();

    private final String target = "/";
    private final String target_error = "/WEB-INF/account/login.jsp";

    @Override
    protected boolean validate_input(Map<String, String[]> map) {
        return true;
    }

    @Override
    protected boolean validate_logic() {
        UserNameValidator userNameValidator = new UserNameValidator(errorMap, correctMap);
        if (userNameValidator.validate(map, "nickname")) {
            System.out.println("Correct validesion of nickname : " + correctMap.get("nickname"));
        }
        UserNameValidator password = new UserNameValidator(errorMap, correctMap);
        if (password.validate(map, "password")) {
            System.out.println("Correct possword : " + correctMap.get("password"));
        }
//        SkipValidator userNameValidator = new SkipValidator(errorMap, correctMap);
//        if (userNameValidator.validate(map, "nickname")) {
//            System.out.println("Correct validesion of nickname");
//        }
//        SkipValidator passwordValidator = new SkipValidator(errorMap, correctMap);
//        if (passwordValidator.validate(map, "password")) {
//            System.out.println("Correct possword");
//        }

        return errorMap.isEmpty();
    }

    @Override
    protected boolean try_execute() {
        try {
            User findByNickName = dao.findByNickName(correctMap.get("nickname"));

            if (findByNickName == null) {
                errorMap.addError("account", "Invalid account");
                return false;
            } else {
                String username1 = correctMap.get("nickname");
                String password1 = correctMap.get("password");

                //   GenerateHashing  passwordHash = new GenerateHashing() ;
                //    String newpass = passwordHash.GeneratePassword(username1, "Legend");
                String username2 = findByNickName.getNickname();
                String password2 = findByNickName.getPassword();

                if (username1.equals(username2) && password1.equals(password2)) {
                    HttpSession session = request.getSession(true);
                    session.setAttribute("sessionuser", findByNickName);

                    List<Role> roleList = findByNickName.getRoleList();

                    for (Role r : roleList) {
                        if (r.getId() == 1) { // admin
                            session.setAttribute("isadmin", true);
                        }
                        if (r.getId() == 2) { // ownder
                            session.setAttribute("isowner", true);
                            session.setAttribute("isvisitor", true);
                        }
                        if (r.getId() == 3) { // visitor
                            session.setAttribute("isvisitor", true);
                        }
                    }

                    return true;
                } else {
                    errorMap.addError("account", "Invalid credentials");
                    return false;
                }
            }
        } catch (Exception e) {
            errorMap.addError("exception", e.getMessage());
            return false;
        }
    }

    @Override
    protected void on_success() {
        redirect(target);
    }

    @Override
    protected void on_error() {
        request.setAttribute("errorMap", errorMap);
        redirect(target_error);
    }

}

Airbnb/GreekTravel/src/java/controllers/account/LogoutController.java
package controllers.account;

import java.util.Map;
import javax.servlet.http.HttpSession;


public class LogoutController extends controllers.Controller{
    private final String target = "/";
    private final String target_error =  "/WEB-INF/index.jsp";
    
    @Override
    protected boolean validate_input(Map<String, String[]> map) {
        return true;
    }

    @Override
    protected boolean validate_logic() {
        return true;
    }

    @Override
    protected boolean try_execute() {
        HttpSession session = request.getSession();
        
        session.removeAttribute("sessionuser");
        session.removeAttribute("isowner");
        session.removeAttribute("isadmin");
        session.removeAttribute("isvisitor");
        
        session.invalidate();
        
        return true;        
    }

     @Override
    protected void on_success() {
        redirect(target);
    }

    @Override
    protected void on_error() {
        redirect(target_error);
    }
    
}

Airbnb/GreekTravel/src/java/controllers/account/RegisterController.java
package controllers.account;

import dao.PhotoDAO;
import dao.PhotoDAOImpl;
import dao.UserDAOImpl;
import dao.UserHasRatedDAO;
import dao.UserHasRatedDAOImpl;
import entities.Photo;
import entities.Role;
import entities.User;
import entities.UserHasRated;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import validation.EmailValidator;
import validation.NameValidator;
import validation.PositiveIntegerValidator;
import validation.SkipValidator;
import validation.UserNameValidator;


    public class RegisterController extends controllers.Controller {

    private final String target = "/WEB-INF/report/register_complete.jsp";
    private final String target_error = "/WEB-INF/account/register.jsp";

    private final String defaultPhoto = "http://images6.fanpop.com/image/photos/39500000/Rick-And-Morty-616x480-rick-and-morty-39568274-616-480.png";

    private UserDAOImpl dao = new UserDAOImpl();
    private PhotoDAO pd = new PhotoDAOImpl();
    private UserHasRatedDAO uhrdao = new UserHasRatedDAOImpl();

    @Override
    protected boolean validate_input(Map<String, String[]> map) {

        UserNameValidator userNameValidator = new UserNameValidator(errorMap, correctMap);
        if (userNameValidator.validate(map, "nickname")) {
            System.out.println("Correct validesion of nickname : " + correctMap.get("nickname"));
        }
        UserNameValidator password = new UserNameValidator(errorMap, correctMap);
        if (password.validate(map, "password")) {
            System.out.println("Correct possword : " + correctMap.get("password"));
        }
        UserNameValidator repeat_password = new UserNameValidator(errorMap, correctMap);
        if (repeat_password.validate(map, "repeat_password")) {
            System.out.println("Correct repeat_password");
        }
        NameValidator stringValidetor = new NameValidator(errorMap, correctMap);
        if (stringValidetor.validate(map, "firstname")) {
            System.out.println("Correct firstname : " + correctMap.get("firstname"));
        }
        NameValidator stringValidetorSurname = new NameValidator(errorMap, correctMap);
        if (stringValidetorSurname.validate(map, "surname")) {
            System.out.println("Correct surname : " + correctMap.get("surname"));
        }
        EmailValidator emailValidetor = new EmailValidator(errorMap, correctMap);
        if (emailValidetor.validate(map, "email")) {
            System.out.println("Correct Email : email" + correctMap.get("email"));
        }
        PositiveIntegerValidator phoneNumberValidesion = new PositiveIntegerValidator(errorMap, correctMap);
        if (phoneNumberValidesion.validate(map, "phonenumber")) {
            System.out.println("Correct phonenumber : " + correctMap.get("phonenumber"));
        }
 
        if (map.get("photo")[0] == null || map.get("photo")[0].isEmpty()) {
            correctMap.put("photo", defaultPhoto);
        } else {
            if (map.get("photo")[0].length() < 4000) {
                correctMap.put("photo", map.get("photo")[0]);
            } else {
                errorMap.addError("photo", "Large size of photo");
            }
        }

        SkipValidator isownerValidator = new SkipValidator(errorMap, correctMap);
        isownerValidator.validate(map, "isowner");

        return errorMap.isEmpty();
    }

    @Override
    protected boolean validate_logic() {

        if (!correctMap.get("password").equals(correctMap.get("repeat_password"))) {
            errorMap.addError("repeat_password", "passwords don't matches");
        }
        User user = dao.findByNickName(correctMap.get("nickname"));
        if (user != null) {
            errorMap.addError("nickname", "duplicate username");
        }

        User u = dao.findByEmail(correctMap.get("email"));
        if (u != null) {
            errorMap.addError("email", "duplicate email");
        }
        return errorMap.isEmpty();

    }

    @Override
    protected boolean try_execute() {

        try {
            User u = new User();

            //      configure photo
            List<Photo> photos = new ArrayList<>();
            Photo p = new Photo();
            p.setPhotographUrl(correctMap.get("photo"));
            photos.add(p);

            //       configure roles
            List<Role> roles = new ArrayList<>();
            Role r1 = new Role(3);
            roles.add(r1);

            if (correctMap.get("isowner") != null) {
//                Role r2 = new Role(2);
//            roles.add(r2);
                u.setActive(1);
            } else {
                u.setActive(0);
            }

            //   GenerateHashing  passwordHash = new GenerateHashing() ;
            //   String newpass = passwordHash.GeneratePassword(correctMap.get("password"), "Legend");
            u.setNickname(correctMap.get("nickname"));
            u.setPassword(correctMap.get("password"));
            u.setFirstName(correctMap.get("firstname"));
            u.setSurname(correctMap.get("surname"));
            u.setEmail(correctMap.get("email"));
            u.setPhoneNumber(correctMap.get("phonenumber"));
            u.setPhotoList(photos);
            u.setRoleList(roles);
            //    u.setActive(0);

            Integer newUserId = dao.createWithPhoto(u);
            if (newUserId == null) {
                return false;
            }
//            System.out.println("User object: " + u);

            UserHasRated uhrated = new UserHasRated();
            uhrated.setId(newUserId);
            uhrated.setHasRated(false);
            uhrdao.create(uhrated);

            return true;
        } catch (Exception e) {
            System.out.println("User object: " + e.getMessage());
            // errorMap.addError("exception", e.getMessage());
            return false;
        }

    }

    @Override
    protected void on_success() {
        redirect(target);
    }

    @Override
    protected void on_error() {
        redirect(target_error);
    }
}


       //________________________Skip_validator______________________deletie___
//        SkipValidator userNameValidator = new SkipValidator(errorMap, correctMap);
//        userNameValidator.validate(map,"nickname");
//        
//        SkipValidator passwordValidator = new SkipValidator(errorMap, correctMap);
//        passwordValidator.validate(map, "password");
//        
//        SkipValidator passwordValidatorRepet = new SkipValidator(errorMap, correctMap);
//        passwordValidatorRepet.validate(map,"repeat_password");
//        
//        SkipValidator stringValidetor = new SkipValidator(errorMap, correctMap);
//        stringValidetor.validate(map, "firstname");
//        
//        SkipValidator stringValidetorSurname = new SkipValidator(errorMap, correctMap);
//        stringValidetorSurname.validate(map, "surname");
//        
//        SkipValidator emailValidetor = new SkipValidator(errorMap, correctMap);
//        emailValidetor.validate(map, "email");
//        
//        SkipValidator phoneNumberValidesion = new SkipValidator(errorMap, correctMap);
//        phoneNumberValidesion.validate(map, "phonenumber");
//        
        //______________________________________________________________________

Airbnb/GreekTravel/src/java/servlets/account/LoginServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servlets.account;

import controllers.account.LoginController;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Map;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author psilos
 */
@WebServlet(name = "LoginServlet", urlPatterns = {"/user/login"})
public class LoginServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        ServletContext servletContext = getServletContext();
        try (PrintWriter out = response.getWriter()) {
            LoginController controller = new LoginController();

            Map<String, String[]> parameterMap = request.getParameterMap();
            
            controller.execute(servletContext, parameterMap, request, response);
        }

    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Airbnb/GreekTravel/web/WEB-INF/account/rating/rating.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@page language="java" %>

<link href="${pageContext.request.contextPath}/css/viewProfile.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/css/button.css" rel="stylesheet" type="text/css" />
     
<head>
    <jsp:include page="/WEB-INF/fragments/common/head.jsp"/>

</head>

<body>
    <div id="wrap">            
        <jsp:include page="/WEB-INF/fragments/common/topbar.jsp"/>

        <jsp:include page="/WEB-INF/fragments/common/header.jsp"/>

        <div id="content">
            <div id="main">               
                <jsp:include page="/WEB-INF/account/rating/rating_details.jsp"/>     
           </div> 
                
            <!--<div id="sidebar">-->
                <%--<jsp:include page="/WEB-INF/fragments/common/sidebar.jsp"/>--%>                                              
            <!--</div>-->
        <jsp:include page="/WEB-INF/fragments/common/footer.jsp"/>
    </div>
</body>

Airbnb/GreekTravel/web/WEB-INF/account/rating/rating_details.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>



<div id="recommendations">
    <div class="tab">
        <h2>Rate Room:</h2>
    </div>
    <div class="container">
        <div class="listing">
            <ul>
                <form  action="${pageContext.request.contextPath}/myrentings/submitrate" method="POST">

                    <li style="display: block; height: 200px; width: 95%;">
                        <div class="listinfo">
                            <img src="${renting.roomId.photoList[0].photographUrl}" alt="Photo" class="listingimage" style=" height: 150px;"/><!--width: 100px;-->
                            <!--<h3>Room id $ {recommendations.key.id};-->

                            <span class="price">Date From: ${renting.dateFrom}</span> 
                            <span class="price">Date To: ${renting.dateTo}</span>  
                            <br/>
                            
                            
                            <span class="rating"> Rate Room: 
                                <input type="radio" class="rating-input" value="5" 
                                       id="rating-input-2-5" name="ratingRoom">
                                <label for="rating-input-2-5" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="4" 
                                       id="rating-input-2-4" name="ratingRoom">
                                <label for="rating-input-2-4" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="3" 
                                       id="rating-input-2-3" name="ratingRoom">
                                <label for="rating-input-2-3" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="2" 
                                       id="rating-input-2-2" name="ratingRoom">
                                <label for="rating-input-2-2" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="1" 
                                       id="rating-input-2-1" name="ratingRoom">
                                <label for="rating-input-2-1" class="rating-star"></label>
                            </span>
                            <c:forEach items="${errorMap.ratingRoom}" var="obj">
                                <p class="fielderror">${obj}</p>
                            </c:forEach>
                            <br/>
                            <span class="rating">Rate Owner:
                                <input type="radio" class="rating-input" value="5" 
                                       id="rating-input-1-5" name="ratingOwner">
                                <label for="rating-input-1-5" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="4" 
                                       id="rating-input-1-4" name="ratingOwner">
                                <label for="rating-input-1-4" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="3" 
                                       id="rating-input-1-3" name="ratingOwner">
                                <label for="rating-input-1-3" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="2" 
                                       id="rating-input-1-2" name="ratingOwner">
                                <label for="rating-input-1-2" class="rating-star"></label>
                                <input type="radio" class="rating-input" value="1" 
                                       id="rating-input-1-1" name="ratingOwner">
                                <label for="rating-input-1-1" class="rating-star"></label>
                            </span>
                            <c:forEach items="${errorMap.ratingOwner}" var="obj">
                                <p class="fielderror">${obj}</p>
                            </c:forEach>

                            <div style="margin-bottom: 0px; margin-right: 11px;">
                                <button name="rentingId" type="submit" value="${renting.id}">Rate</button>
                            </div>
                    </li>
                </form>
            </ul>
        </div>
    </div>
</div>